GET http://localhost:8080/getAllList
####

POST http://localhost:8080/addList
Content-Type: application/json

{
    "listName":"chintu Kulkarni"
}
####

POST http://localhost:8080/register
Content-Type: application/json

{
    "fName":"prathmesh",
    "email":"prathmesh12@gmail.com",
    "password":"prathmesh",
    "mobile":"8421823948"
}
####

DELETE http://localhost:8080/deleteList
Content-Type: application/json

{
    "id":"600c5f79ec9d985954030e5f"
}